In [1]:
import pandas as pd
import numpy as np
import time
import gc

In [2]:
path = '/home/kai/data/kaggle/talkingdata/data/'
train = pd.read_csv(path + 'train_cleaned_final.csv')
test = pd.read_csv(path + 'test_cleaned_final.csv')

In [8]:
df_all = pd.concat([train,test])

# Get Train on Day7 Day8 Day9

In [3]:
df_hour = pd.read_csv(path+'hourdistri.csv', index_col='Unnamed: 0')
index = {}
for day in ['day7', 'day8','day9']:
    index[day] = list(range(df_hour.loc[day,'4start'], df_hour.loc[day,'6end0sec'])) + \
    list(range(df_hour.loc[day,'9start'], df_hour.loc[day,'11end0sec'])) + \
    list(range(df_hour.loc[day,'13start'], df_hour.loc[day,'15end0sec']))

In [9]:
for file in ['day7', 'day8', 'day9','test']: 
    print(len(df_dict[file]))

19534560
20446743
20898422
18790469

# Define functin

In [12]:



def col_name(cols, func=None):
    if func is None:
        return '_'.join(cols)
    else:
        return '_'.join(cols) + '_' + func.__name__
    
orders = {}
feature_col = ['ip', 
              'app', 
              'device', 
              'os', 
              'channel',
              'day',
              'hour',]

# feature_col = ['ip', 
#               'app', 
#               'device', 
#               'os', 
#               'channel']
for col in feature_col:
    orders[col] = 10 ** (int(np.log(max(train[col].max(),test[col].max() ) + 1) / np.log(10)) + 1)
def get_group(df, cols):
    """
    define an encoding method which can ganrantee the adding value will be unique.
    eg: artist_name_composer will be a combination of (artist_name,composer) and the encoding will reflect the unqiue combination of those two
    """
    group = df[cols[0]].copy()
    for col in cols[1:]:
        group = group * orders[col] + df[col]
        
        
    return group

# Feature Engineering

In [13]:
from itertools import combinations
from sklearn.preprocessing import LabelEncoder
scale = 10
target='is_attributed'

df_result = {day:pd.DataFrame() for day in ['day7', 'day8', 'day9', 'test']}

combine_col = ['app','device','os']
for num_comb in [2,3]:
    for cols in combinations(combine_col, num_comb):
        feature_name = col_name(cols)
        print(feature_name)
        group = get_group(df_all, cols)
        encoder = LabelEncoder()
        print('fit encoder')
        encoder.fit(group.values)
        for day in ['day7', 'day8', 'day9', 'test']:
            print(day)
            if day != 'test':
                df_result[day][feature_name] = encoder.transform(group.iloc[index[day]])
            else:
                df_result[day][feature_name] = encoder.transform(group.iloc[-len(test):])
                
#     encode 4
feature_name = col_name(['app','device','os','channel'])
print(feature_name)
group = get_group(df_all, cols)
encoder = LabelEncoder()
print('fit encoder')
encoder.fit(group.values)
for day in ['day7', 'day8', 'day9', 'test']:
    print(day)
    if day != 'test':
        df_result[day][feature_name] = encoder.transform(group.iloc[index[day]])
    else:
        df_result[day][feature_name] = encoder.transform(group.iloc[-len(test):])

app_device
fit encoder
day7
day8
day9
test
app_os
fit encoder
day7
day8
day9
test
device_os
fit encoder
day7
day8
day9
test
app_device_os_channel
fit encoder
day7
day8
day9
test
app_device_os
fit encoder
day7
day8
day9
test
app_device_os_channel
fit encoder
day7
day8
day9
test

# Saving

In [24]:
load_path = '/home/kai/data/kaggle/talkingdata/wl/data/equalhour/'
file_format = '{}_categorymore_V1.csv'
for file in ['day7', 'day8', 'day9','test']: 
    df_result[file].to_csv(load_path+file_format.format(file), index=False)
    print(file_format.format(file))

day7_categorymore_V1.csv
day8_categorymore_V1.csv
day9_categorymore_V1.csv
test_categorymore_V1.csv

In [23]:
df_result['day7']

          app_device  app_os  device_os  app_device_os_channel  app_device_os
0                367    2580         51                   4515           4515
1                367    2581         52                   4516           4516
2                410    3872         51                   6652           6652
3                389    3394         44                   5839           5839
4                304     753         42                   1447           1447
5                360    2319         53                   4108           4108
6                304     760         49                   1454           1454
7                297     248         40                    749            749
8                304     758         47                   1452           1452
9                297     255         47                    756            756
10               367    2600         71                   4535           4535
11               297     261         53                    762            762
12               304     764         53                   1458           1458
13               304     777         66                   1471           1471
14               304     751         40                   1445           1445
15              3916    5453         47                  13507          13507
16               381    3126         50                   5391           5391
17               304     766         55                   1460           1460
18               291      33        828                    569            569
19               297     261         53                    762            762
20               410    3868         47                   6648           6648
21               297     261         53                    762            762
22               304     758         47                   1452           1452
23               381    3129         53                   5394           5394
24               381    3137         61                   5402           5402
25               410    3868         47                   6648           6648
26               389    3401         51                   5846           5846
27               304     773         62                   1467           1467
28               367    2573         44                   4508           4508
29               304     758         47                   1452           1452
...              ...     ...        ...                    ...            ...
19534530       10242   10565          0                  26668          26668
19534531         367    2573         44                   4508           4508
19534532         297     259         51                    760            760
19534533         367    2576         47                   4511           4511
19534534         389    3410         60                   5855           5855
19534535         367    2584         55                   4519           4519
19534536         298     278        844                   1263           1263
19534537         389    3404         54                   5849           5849
19534538         381    3129         53                   5394           5394
19534539         360    2337         71                   4126           4126
19534540         297     261         53                    762            762
19534541         297     261         53                    762            762
19534542         304     758         47                   1452           1452
19534543         389    3398         48                   5843           5843
19534544         360    2317         51                   4106           4106
19534545         297     263         55                    764            764
19534546         304     781         70                   1475           1475
19534547         410    3874         53                   6654           6654
19534548        3901    5105         70                  12892          12892
19534549         346    1886         70                   3396           3396
19534550         367    2582         53                   4517           4517
19534551         297     261         53                    762            762
19534552         367    2576         47                   4511           4511
19534553         297     259         51                    760            760
19534554         389    3402         52                   5847           5847
19534555         381    3129         53                   5394           5394
19534556         304     781         70                   1475           1475
19534557         297     273         65                    774            774
19534558         297     263         55                    764            764
19534559         410    3869         48                   6649           6649

[19534560 rows x 5 columns]

In [4]:
## load category col
load_path = '/home/kai/data/kaggle/talkingdata/wl/data/equalhour/'
file_format = '{}_category_discrete_scale10_new.csv'
df_dict_cat = {}
for file in ['day7', 'day8', 'day9','test']: 
    df_dict_cat[file] = pd.read_csv(load_path+file_format.format(file))
    print(file_format.format(file))

day7_category_discrete_scale10_new.csv
day8_category_discrete_scale10_new.csv
day9_category_discrete_scale10_new.csv
test_category_discrete_scale10_new.csv

In [6]:
df_dict_cat['test'].ip.value_counts()

 1     16704143
-1      1527103
 0       553812
 2         1945
 3         1149
 11         768
 4          639
 6          580
 5          143
 7           76
 10          46
 8           37
 9           28
Name: ip, dtype: int64

In [11]:
for file in ['day7', 'day8', 'day9','test']: 
    print(len(df_dict_cat[file]))

19534560
20446743
20898422
18790469