In [1]:
import pandas as pd
import numpy as np

In [19]:
count = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance_train_count_all_0405_combine5_61.csv', header=None)
count21 = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance_train_count_all_0404_scale21.csv', header=None)
mean = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance_train_mean_all_0405_combine5.csv', header=None)
mean21 = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance_train_mean_scale21.csv', header=None)
reversemean = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance_train_reversemean_all_0405_combine5.csv', header=None)
sub_count = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance_just_count75m_0404.csv', header=None)

sub_75 = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance__countAndmean75m_0404_shuffleVal.csv', header=None)

count_1 = pd.read_csv('/home/kai/data/kaggle/talkingdata/wl/data/output/importance__only_count_submission0406.csv', header=None)

In [22]:
count.head(50)

                                     0    1
0                              channel  544
1                                 hour  360
2                                  app  318
3                                   os  303
4                             ip_count  138
5                      ip_device_count   70
6                         ip_day_count   62
7                    app_channel_count   43
8                  ip_device_day_count   39
9             ip_device_intesthh_count   36
10                ip_device_hour_count   36
11                   ip_intesthh_count   34
12                     device_os_count   32
13              ip_hour_intesthh_count   32
14               ip_day_intesthh_count   31
15                  ip_device_os_count   31
16                         ip_os_count   31
17            ip_app_os_day_hour_count   29
18                        ip_app_count   28
19        ip_device_day_intesthh_count   28
20                  app_day_hour_count   27
21                ip_os_day_hour_count   26
22              ip_device_os_day_count   26
23                    ip_app_day_count   25
24         ip_device_os_intesthh_count   24
25            ip_os_day_intesthh_count   23
26           app_os_channel_hour_count   22
27       app_os_channel_day_hour_count   22
28                 device_os_day_count   21
29                           app_count   21
30                 ip_app_os_day_count   20
31          app_channel_day_hour_count   20
32            ip_device_day_hour_count   19
33              os_hour_intesthh_count   19
34         ip_app_device_channel_count   18
35                ip_os_intesthh_count   18
36            device_os_day_hour_count   18
37  os_channel_day_hour_intesthh_count   17
38              ip_app_device_os_count   17
39                    app_device_count   17
40     ip_device_os_day_intesthh_count   16
41        app_device_os_intesthh_count   16
42     app_channel_hour_intesthh_count   16
43   app_os_channel_day_intesthh_count   16
44                app_device_day_count   16
45            device_os_intesthh_count   15
46          ip_app_device_os_day_count   15
47                              device   15
48        ip_os_channel_day_hour_count   15
49   app_device_os_hour_intesthh_count   14

In [20]:
count_1.head(21)

                           0    1
0                    channel  985
1                         os  644
2                        app  598
3                       hour  318
4      ip_day_intesthh_count  245
5   ip_app_os_day_hour_count  209
6          ip_day_hour_count  198
7         app_day_hour_count  126
8       ip_os_day_hour_count  119
9      ip_app_day_hour_count  101
10                    device   63

In [24]:
all_features = []
# features_count = ['ip_count', 
#                   'ip_minute_count', 
#                   'app_channel_count', 
#                   'ip_app_count', 
#                   'ip_app_hour_count', 
#                   'ip_second_count', 
#                   'ip_app_os_count', 
#                   'ip_device_hour_count', 
#                   'ip_os_hour_count',
#                   'ip_day_hour_count',
#                   'ip_channel_count', 
#                   'app_channel_day_count', 
#                   'ip_device_count', 
#                   'ip_day_count', 
#                   'ip_hour_count']
features_count = ['ip_day_intesthh_count', 
                  'ip_day_hour_count', 
                  'ip_os_day_hour_count' ,
                  'ip_app_day_hour_count', 
                  'ip_app_os_day_hour_count', 
                  'app_day_hour_count',
                 
                 'app_channel_count']
weight = [31, 4, 26, 3, 29, 27]
###########################################################################
#plus
features_count = ['ip_day_intesthh_count', 
                  'ip_day_hour_count', 
                  'ip_os_day_hour_count' ,
                  'ip_app_day_hour_count', 
                  'ip_app_os_day_hour_count',  
                  'app_day_hour_count', 
                  
                  'ip_device_count', 
                  'app_channel_count',
                  'ip_device_os_count',
                  
                  
                 ]


weight = [31, 4, 26, 3, 29, 27, 70, 43, 31]
#############################################################################
#plusplus
features_count = ['ip_day_intesthh_count', 
                  'ip_day_hour_count', 
                  'ip_os_day_hour_count' ,
                  'ip_app_day_hour_count', 
                  'ip_app_os_day_hour_count',  
                  'app_day_hour_count', 
                  
                  'ip_device_count', 
                  'app_channel_count',
                  'ip_device_os_count',
                  
                  'ip_count',
                  'ip_device_intesthh_count', 
                  'ip_device_hour_count',
                  'ip_intesthh_count',
                  'ip_device_day_intesthh_count',
                  
                  'ip_device_os_intesthh_count',
                  'app_os_channel_day_hour_count',
                  'ip_app_device_channel_count'
                 ]

###############################################################################
features_count = ['ip_day_intesthh_count', 
                  'ip_day_hour_count', 
                  'ip_os_day_hour_count' ,
                  'ip_app_day_hour_count', 
                  'ip_app_os_day_hour_count', 
                  'app_day_hour_count',
                 
                 'app_channel_count',  #0.9705
                  
                 'device_os_count',
                  'ip_device_day_intesthh_count', 
                  'app_os_channel_hour_count', 
                  'app_day_hour_count', 
                  'app_os_channel_hour_count', 
                  'device_os_day_count', 
                  'app_channel_day_hour_count', 
                  'os_hour_intesthh_count', 
                  'device_os_day_hour_count'
                 ]


weight = [31, 4, 26, 3, 29, 27, 70, 43, 31, 138, 36, 36, 34, 28]




features_mean = ['ip_mean', 
                'app_os_channel_mean', 
                'hour_minute_second_mean', 
                'app_os_hour_mean', 
                'ip_second_mean', 
                'ip_app_device_mean', 
                'device_minute_second_mean', 
                'ip_app_mean',
                'ip_channel_mean',
                'device_minute_mean',
                'app_channel_hour_mean', 
                 'app_device_os_mean' ,
                 'device_os_hour_mean', 
                 'ip_app_channel_mean']
features_mean = []
# features_ori = ['channel', 'app', 'os', 'device', 'second','minute', 'hour', 'ip']
features_ori = ['channel', 'app', 'os', 'device', 'hour', ]

# Alexey's lightgbm
# predictors = ['ip', 'device', 'app', 'os', 'channel', 'hour', 
#               'ip_day_hour','count_by_ip','ip_app_count', 'ip_app_os_count',
#               "ip_hour_channel", "ip_hour_os", "ip_hour_app","ip_hour_device"]

 
#               
#               "ip_hour_channel", ]




all_features.extend(features_count)
all_features.extend(features_mean)
all_features.extend(features_ori)

In [25]:
import json as js
file = '/home/kai/data/kaggle/talkingdata/wl/data/features/feature_cols.json'
with open(file, 'w') as myjs:
    js.dump(all_features, myjs)
    
    
# with open(file, 'r') as myjs:
#     my = js.load(myjs)

In [10]:
count[count[0] == 'app_day_hour_count']

                     0   1
20  app_day_hour_count  27

In [4]:
count_nonscale[count_nonscale[0] == 'ip_day_hour_count']

                    0    1
13  ip_day_hour_count  119

In [12]:
df1 = pd.DataFrame({'a':[1,2], 'b':[3,4], 'c': [5,6]})
df2 = pd.DataFrame({'c':[13,14], 'a':[11,12]})

In [13]:
df1

   a  b  c
0  1  3  5
1  2  4  6

In [14]:
df2

    a   c
0  11  13
1  12  14

In [15]:
pd.concat([df1, df2])

    a    b   c
0   1  3.0   5
1   2  4.0   6
0  11  NaN  13
1  12  NaN  14

In [16]:
def aa(x):
    return x

In [17]:
aa.__name__

'aa'